app/urls.py
from django.conf.urls import url, include
from django.views.generic.base import TemplateView
from .views import product_view, register_view, delete_product_view, data_product_view
from .views import update_product_view, create_product_view, home_view, order_product_name_view
from .views import order_product_price_view, order_product_stock_view


urlpatterns = [
    url(r'^products', product_view, name='products'),
    url(r'^register', register_view, name='register'),
    url(r'^delete_product/(?P<pk>.*)', delete_product_view, name='del'),
    url(r'^edit_product/(?P<pk>.*)', update_product_view, name='edit'),
    url(r'^create_product', create_product_view, name='create-product'),
    url(r'^home', home_view, name='home'),
    url(r'^graphicdata', data_product_view, name='graphicdata'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^order_name/', order_product_name_view, name='order_name'),
    url(r'^order_price/', order_product_price_view, name='order_price'),
    url(r'^order_stock/', order_product_stock_view, name='order_stock'),
    url('', TemplateView.as_view(template_name='index.html'), name='index'),
]

manager/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('app.urls'))
]

admin.site.site_header = "ESoft"
admin.site.site_title = "Desafio"
admin.site.index_title = "Sistema de gerenciamento"

app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("O email é obrigatório")
        email = self.normalize_email(email)
        user = self.model(email=email, username=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password, **extra_fields):
        extra_fields.setdefault(str("is_superuser"), True)
        extra_fields.setdefault(str("is_staff"), True)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault(str("is_superuser"), True)
        extra_fields.setdefault(str("is_staff"), True)

        if extra_fields.get(str("is_superuser")) is not True:
            raise ValueError('Superuser precisa ter is_superuser=true')

        if extra_fields.get(str("is_staff")) is not True:
            raise ValueError('Staff precisa ter is_staff=true')

        return self._create_user(email, password, **extra_fields)


class CustomUser(AbstractUser):
    name = models.CharField("Nome", max_length=20)
    email = models.EmailField("E-mail", unique=True)
    zipcode = models.CharField("CEP", max_length=8, default="Ex: 72800000")
    address = models.CharField("Endereço", max_length=20, default="Ex: Rua 21 de Abril")
    number = models.CharField("Número", max_length=4, default="Ex: 25")
    complement = models.CharField("Complemento", max_length=20, default="Ex: Setor sul")
    district = models.CharField("Bairro", max_length=20, default="Ex: Ipanema")
    city = models.CharField("Cidade", max_length=20, default="Ex: Rio de Janeiro")
    state = models.CharField("Estado", max_length=20, default="Ex: RJ")

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    objects = UserManager()


class Product(models.Model):
    name = models.CharField("Nome", max_length=15)
    price = models.DecimalField("Preço", decimal_places=2, max_digits=10)
    stock = models.IntegerField("Estoque")

    def __str__(self):
        return self.name

app/forms.py
# -*- coding: utf-8 -*-
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser, Product
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
from django import forms
from django.forms import Field


class CustomUserCreationForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['username'].help_text = ''
        self.fields['password1'].label = 'Senha'
        self.fields['password2'].label = 'Confirmar senha'
        self.fields['password1'].help_text = ''
        self.fields['password2'].help_text = ''

    class Meta:
        model = CustomUser
        fields = ('name', 'username', 'password1', 'password2',
                  'zipcode', 'address', 'number', 'complement',
                  'district', 'city', 'state')
        labels = {'username': 'Login', 'password1': 'Senha', 'password2': 'Confirmar senha'}
        UserCreationForm.error_messages = {'password_mismatch': 'As senhas não combinam'}
        widgets = {
            'zipcode': forms.TextInput(attrs={"id": "id_zipcode", "onblur": "getAddressFields()"}),
        }
        Field.default_error_messages = {'required': ""}

    def save(self, commit=True):
        user = super(CustomUserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.email = self.cleaned_data['username']
        user.is_staff = True
        user.is_superuser = True
        if commit:
            user.save()
        return user


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('name', 'city')


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'price', 'stock')

    def clean(self):
        price = self.cleaned_data['price']
        stock = self.cleaned_data['stock']

        if price < 0:
            raise ValueError(_("O preço do produto não pode ser menor do que zero."))

        if stock < 0:
            raise ValueError(_("A quantidade em estoque não pode ser menor que zero."))

app/views.py
# -*- coding: utf-8 -*-
import json
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from .models import Product
from .forms import CustomUserCreationForm, ProductForm
from django.contrib import messages


def product_view(request):
    products = Product.objects.all()
    context = {
        'products': products
    }
    return render(request, 'products.html', context)


def create_product_view(request):
    form = ProductForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            messages.success(request, 'Produto salvo com sucesso!')
            return redirect('products')
        else:
            messages.error(request, 'Erro ao cadastrar produto.')


def update_product_view(request, pk):
    product = get_object_or_404(Product, pk=pk)
    form = ProductForm(request.POST or None, instance=product)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            messages.success(request, 'Produto atualizado com sucesso!')
            return redirect('products')
        else:
            messages.error(request, 'Erro ao atualizar produto.')


def delete_product_view(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if product:
        product.delete()
        return redirect('products')


def register_view(request):
    form = CustomUserCreationForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            form = CustomUserCreationForm()
            return redirect('index')
        else:
            messages.error(request, 'Erro ao cadastrar usuário.')
    else:
        form = CustomUserCreationForm()

    context = {
        'form': form
    }
    return render(request, 'register.html', context)


def home_view(request):
    return render(request, 'home.html')


def data_product_view(request):
    queryset = Product.objects.all()
    product_name = [product.name for product in queryset]
    product_stock = [product.stock for product in queryset]

    context = {
        'names': product_name,
        'stock': product_stock
    }
    return HttpResponse(json.dumps(context))


def order_product_name_view(request):
    queryset = Product.objects.order_by('name')
    context = {
        'products': queryset
    }
    print context
    return render(request, 'products.html', context)


def order_product_price_view(request):
    queryset = Product.objects.order_by('price').reverse()
    context = {
        'products': queryset
    }
    print context
    return render(request, 'products.html', context)


def order_product_stock_view(request):
    queryset = Product.objects.order_by('stock').reverse()
    context = {
        'products': queryset
    }
    print context
    return render(request, 'products.html', context)

app/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit-no">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.bundle.js"></script>
    <link href="{% static 'css/home.css' %}" rel="stylesheet">
    <title>Home</title>
</head>
<body onload="getProductData()">
    {% if user.is_authenticated %}
    <header class="header">
        <a id="home" class="btn btn-primary" href="{% url 'index' %}">Home</a>
        <a id="products" class="btn btn-primary" href="{% url 'products' %}">Produtos</a>
        <a id="logout" class="btn btn-primary" href="{% url 'logout' %}">Sair</a>
    </header>

    <main>
        <div class="container">
            <canvas id="graphic" width="400" height="200"></canvas>
        </div>
    </main>
    {% else %}
        <h2 style="padding-left: 15%; margin-top: 20%;">Você não está logado. Faça login para visualizar a página.</h2>
        <a style="margin-left: 45%;" class="btn btn-primary" href="{% url 'login' %}">Login</a>
    {% endif %}

</body>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="{% static 'js/home.js' %}"></script>
</html>

app/templates/products.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/products.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <title>Produtos</title>
</head>
<body>

  {% if user.is_authenticated %}
  <header class="header">
      <button id="registerbutton" type="button" class="btn btn-primary" data-toggle="modal" data-target="#createProductModal" data-whatever="">Cadastrar</button>
      <div class="modal fade" id="createProductModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
              <div class="modal-content">
                  <div class="modal-header">
                      <h5 class="modal-title" id="createProductModal">Cadastrar produto</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                      </button>
                  </div>
                  <div class="modal-body">
                      <form method="post" action="{% url 'create-product' %}">
                          {% csrf_token %}
                          {{ form.price.errors }}
                          <div class="form-group">
                              <label for="id_name" class="col-form-label">Nome:</label>
                              <input type="text" class="form-control" id="id_name" name="name" value="{{ product.name }}">
                          </div>
                          <div class="form-group">
                              <label for="id_price" class="col-form-label">Preço:</label>
                              <input class="form-control" id="id_price" name="price" value="{{ product.price }}">
                          </div>
                          <div class="form-group">
                              <label for="id_stock" class="col-form-label">Estoque:</label>
                              <input class="form-control" id="id_stock" name="stock" value="{{ product.stock }}">
                          </div>
                          <div class="modal-footer">
                              <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                              <button type="submit" class="btn btn-primary">Cadastrar</button>
                          </div>
                      </form>
                  </div>
              </div>
          </div>
      </div>
  </header>
  <main>

  <h1>Produtos</h1>

  <div class="order">
      <span id="labelOrder">Ordernar por: </span>
      <a href="{% url 'order_name' %}"><button id="name" class="btn btn-primary" onclick="orderByName()">Nome</button></a>
      <a href="{% url 'order_price' %}"><button id="price" class="btn btn-primary">Preço</button></a>
      <a href="{% url 'order_stock' %}"><button id="stock" class="btn btn-primary">Estoque</button></a>
  </div>

    <table class="table">
        <thead class="thead-light">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Nome</th>
                <th scope="col">Preço</th>
                <th scope="col">Estoque</th>
                <th scope="col">Editar</th>
                <th scope="col">Excluir</th>
            </tr>
        </thead>
        <tbody>
        {% for product in products %}
            <tr>
                <td>{{ product.id }}</td>
                <td>{{ product.name }}</td>
                <td>{{ product.price }}</td>
                <td>{{ product.stock }}</td>
                <td>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#editProductModal{{ product.pk }}" data-whatever="{{ product.pk }}">Editar</button>
                    <div class="modal fade" id="editProductModal{{ product.pk }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                          <div class="modal-dialog" role="document">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h5 class="modal-title" id="editProductModal">Editar produto</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                                </button>
                              </div>
                              <div class="modal-body">
                                <form method="post" action="{% url 'edit' product.pk %}">
                                  {% csrf_token %}
                                  <div class="form-group">
                                    <label for="id_name" class="col-form-label">Nome:</label>
                                    <input type="text" class="form-control" id="id_name" name="name" value="{{ product.name }}">
                                  </div>
                                  <div class="form-group">
                                    <label for="id_price" class="col-form-label">Preço:</label>
                                    <input class="form-control" id="id_price" name="price" value="{{ product.price }}">
                                  </div>
                                  <div class="form-group">
                                    <label for="id_stock" class="col-form-label">Estoque:</label>
                                    <input class="form-control" id="id_stock" name="stock" value="{{ product.stock }}">
                                  </div>
                                  <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                                    <button type="submit" class="btn btn-primary">Editar</button>
                                  </div>
                                </form>
                              </div>
                            </div>
                          </div>
                    </div>
                </td>
                <td>
                    <a href="{% url 'del' product.pk %}">
                        <button class="btn btn-danger">Delete</button>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
  </main>
  {% else %}
        <h2 style="padding-left: 15%; margin-top: 20%;">Você não está logado. Faça login para visualizar a página.</h2>
        <a style="margin-left: 45%;" class="btn btn-primary" href="{% url 'login' %}">Login</a>
  {% endif %}
</body>
<script src="{% static 'js/products.js' %}" ></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</html>

app/templates/register.html
{% load static %}
{% load bootstrap %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
    <title>Cadastro</title>
</head>
<body>
<h1>Cadastro de usuário</h1>
    <div class="container">
        <form method="post" action="{% url 'register' %}">
            {% csrf_token %}
            {{ form|bootstrap }}
            <input type="submit" id="registerButton" class="btn btn-primary" value="Cadastrar">
        </form>
    </div>
</body>
<script src="{% static 'js/register.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>ESoft</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit-no">
    <link rel="icon" href="https://www.geekuniversity.com.br/static/images/favicon.4fcb819d32bf.ico">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link href="https://getbootstrap.com/docs/4.0/examples/sign-in/signin.css" rel="stylesheet">
</head>
<body class="text-center">
    {% block content %}{% endblock %}
</body>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit-no">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
</head>

<body class="text-center" onload="getYear()">

    <header class="header">
        <a id="home" class="btn btn-primary" href="{% url 'home' %}">Home</a>
        <a id="login" class="btn btn-primary" href="{% url 'login' %}">Login</a>
        <a id="register" class="btn btn-primary" href="{% url 'register' %}">Cadastrar</a>
    </header>

    <main>
          <form>
              <div class="form-group">
                <label id="nameLabel" for="formGroupExampleInput">Nome</label>
                <input type="text" readonly class="form-control" id="formGroupExampleInput" value="Divino Luiz Barbosa Moreira">
              </div>
              <div class="form-group">
                <label id="emailLabel" for="formGroupExampleInput2">E-mail</label>
                <input type="text" readonly class="form-control" id="formGroupExampleInput2" value="divino.lzbm@gmail.com">
              </div>
              <div class="form-group">
                <label id="gitLabel" for="formGroupExampleInput3">GitHub</label>
                <input type="text" readonly class="form-control" id="formGroupExampleInput3" value="https://github.com/DLuizBM">
              </div>
              <div class="form-group">
                <label id="inLabel" for="formGroupExampleInput3">LinkedIn</label>
                <input type="text" readonly class="form-control" id="formGroupExampleInput3" value="https://www.linkedin.com/in/divino-luiz-barbosa-moreira-961082194/">
              </div>
            </form>
    </main>

    <footer class="footer">
        <span class="info" id="info"></span>
    </footer>

</body>
<script src="{% static 'js/index.js' %}"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</html>